
@extends('frontend.layouts.master')
@section('title','PAGE D ACCEUIL')
<head> <link rel="stylesheet" href="frontend/css/landing.css" /> </head>
@section('content')
<main>
      <img class="banniere" src="frontend/img/banniere.jpg" alt="">
   

      <div class="slider">
        <div class="slide">
          <div id="div1">
            <img src="frontend/img/div2.jpg" alt="" />
          </div>
          <div id="div2">
            <h2>
               Nutritional program generated by linear optimisation.
            </h2>
            <b
              ><i class="fa fa-solid fa-user"></i> What are the benefits ?
            </b>
            <li>Tailored diet for men and women</li>
            <li>Calculation of calories to consume each day</li>
            <li>
              An adequate diet for all ages, weights, daily activities
              ...
            </li>
            <button
              class="btn_essayer"
              onclick="location.href='{{url('/information')}}'"
            >
              <p>Start</p>
            </button>
          </div>
        </div>
        <div class="slide">
          <div id="div1">
            <img src="frontend/img/div1.jpg" alt="" />
          </div>
          <div id="div2">
            <h2>A specific diet according to the caloric need.</h2>
            <b
              ><i class="fa fa-solid fa-user"></i> What are the benefits ?
            </b>
            <li>Menus made up of a wide variety of products.</li>
            <li>A quick result : reach your goals in 12 weeks.</li>
            <li>
              The menus vary according to calories, proteins, carbohydrates <br> and total fat.
            </li>
            <button
              class="btn_essayer"
              onclick="location.href='{{url('/information')}}'"
            >
              <p>Start</p>
            </button>
          </div>
        </div>
        <div class="slide">
          <div id="div1">
            <img src="frontend/img/Bodybuilding-Workouts.jpg" alt="" />
          </div>

          <div id="div2">
            <h2>Sports program adapted for all peoples</h2>
            <b><i class="fa fa-solid fa-user"></i> What are the benefits </b>
            <li>Musculation programs for men and women.</li>
            <li>
              Musculation programs for weight loss, weight gain and weight maintain.
            </li>
            <li>
              More than 90 bodybuilding exercises videos by
              categories.
            </li>
            <button
              class="btn_essayer"
              onclick="location.href='{{url('/information')}}'"
            >
              <p>Start</p>
            </button>
          </div>
        </div>
      </div>
      <div class="dots"></div>
      <button class="slider__btn slider__btn--left">&#8249;</button>
      <button class="slider__btn slider__btn--right">&#8250;</button>
      <!--

      <div class="slider_2">
        <div class="slide_2">
          <img src="frontend/img/ben-jackson-before-after-gros-remove.png" alt="">
        </div>
        <div class="slide_2">
          <img src="frontend/img/ben-jackson-before-after-remove.png" alt="">
          </div>
        </div>
        </div>
      </div>
      <div class="dots_2"></div>
      <div class="temo"><p>faite comme amar il a perdu 80kg c est trop cool</p></div>
    -->
<script  src="frontend/js/slider.js"></script>        
</main>
@endsection